// <auto-generated />
namespace CSharpEgitimKampi301.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mgProductPrice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mgProductPrice));
        
        string IMigrationMetadata.Id
        {
            get { return "202412101840450_mg-ProductPrice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
